#!/bin/bash
#
# List all files not tracked by git (including the .git repository) in a
# regular-expression format expected by CMake/CPack. This will be passed
# to CPack's CPACK_IGNORE_FILES variable for ignoring while making the
# source/binary packages, and also stored in .cpackignore file.
#
# If there's no .git directory, or git is not installed, look for
# .cpackignore file.  This may happen if we're building the source outside
# of a git repository (or if there's no git on the system).
#
# Usage: git-untracked-files [dir_from_which_to_run]
#

test "x$1" != "x" && cd "$1"

{ which git 2>&1 > /dev/null && test -d .git; } || { test -f .cpackignore && cat .cpackignore && exit; } || exit -1;

echo -n '/\\.git;' | tee -a .cpackignore
git clean -ndx | grep "Would remove" | cut -b 14- \
	| sed '/^.cpackignore$/d' \
	| sed '/^.version$/d' \
	| awk '{ print "/"$0 }' \
	| sed 's/\./\\\\./g' \
	| tr "\n" ';' \
	| tee -a .cpackignore
