#!/bin/tcsh

#
# PBS invocations
#

#PBS -v SSH_AUTH_SOCK=foo
#PBS -m a
#PBS -l nodes=1:ppn=1
#PBS -j oe

setenv LD_LIBRARY_PATH /scr0/mjuric/usr/lib
setenv CONF_SDSS /scr0/mjuric/galaxy/workspace/$RUNSET/conf.sdss

set ddx = `echo "$DX0 * $NDX" | bc`
set ddx = `printf "%6.3f" $ddx`
setenv RI0 `printf "%5.3f" $RI0`
setenv RI1 `printf "%5.3f" $RI1`
set output = "cache/cylindrical.15.000-21.500.$RI0-$RI1.dx=$ddx.phi0=-180.bin"

echo Runset ID: $RUNSET
echo "Binning ri bin ($RI0, $RI1), dx0=$DX0 ndx=$NDX dx=$ddx"
echo "Output file: $output"

cd /scr0/mjuric/galaxy/workspace/$RUNSET && \
time /scr0/mjuric/usr/bin/bin_volume.x --type=cyl --phi0=-180.000000 \
15.000 21.500 $RI0 $RI1 merged.bin $DX0 $NDX \
"$output"
