#!/bin/tcsh

#
# PBS invocations
#

#PBS -v SSH_AUTH_SOCK=foo
#PBS -m a
#PBS -l nodes=1:ppn=1
#PBS -j oe

setenv LD_LIBRARY_PATH /scr0/mjuric/usr/lib
setenv CONF_SDSS /scr0/mjuric/galaxy/workspace/$RUNSET/conf.sdss

set ddx = `echo "$DX0 * $NDX" | bc`
set ddx = `printf "%6.3f" $ddx`
setenv RI0 `printf "%5.3f" $RI0`
setenv RI1 `printf "%5.3f" $RI1`
set output = "cache/plane.r=15.000-21.500,ri=$RI0-$RI1,dx=$ddx,origin=0.00000,0.00000,0.00000,euler_rot=0.00000,0.00000,0.00000.bin"

echo Runset ID: $RUNSET
echo "Binning ri bin ($RI0, $RI1), dx0=$DX0 ndx=$NDX dx=$ddx"
echo "Output file: $output"

cd /scr0/mjuric/galaxy/workspace/$RUNSET && \
time /scr0/mjuric/usr/bin/bin_volume.x --type=plane 15.000 21.500 $RI0 $RI1 merged.bin $DX0 $NDX \
"$output" \
--coordsys=galcart \
--x1=0.000000,0.000000,0.000000 --x2=1.000000,0.000000,0.000000 \
--x3=0.000000,1.000000,0.000000 --x0=8000.000000,0.000000,0.000000 \
--delta=10000000000.000000 --earthonaxis=0
