#!/bin/tcsh

#
# PBS invocations
#

#PBS -v SSH_AUTH_SOCK=foo
#PBS -m a
#PBS -l nodes=1:ppn=1
#PBS -j oe

echo Runset ID $RUNSET
echo Raytracing and binning run $RUN

setenv LD_LIBRARY_PATH /scr0/mjuric/usr/lib
setenv CONF_SDSS /scr0/mjuric/galaxy/workspace/$RUNSET/conf.sdss

cd /scr0/mjuric/galaxy/workspace/$RUNSET && \
time /scr0/mjuric/usr/bin/raytrace.x   14 22 .1 .15 $RUN 8 && \
time /scr0/mjuric/usr/bin/bin_volume.x 15 21.5 .1 .15 $RUN 8 50
