#!/bin/tcsh

#
# PBS invocations
#

#PBS -v SSH_AUTH_SOCK=foo
#PBS -m a
#PBS -l nodes=1:ppn=1
#PBS -j oe

if(`hostname` == 'caladan.astro.Princeton.EDU' ) then
	echo "Caladan settings."
	setenv WORKSPACE /home/mjuric/projects/galaxy/workspace
	setenv CONF_SDSS $WORKSPACE/$RUNSET/conf.sdss
	setenv BIN /home/mjuric/projects/galaxy/optimized/src
else
	setenv WORKSPACE /scr0/mjuric/galaxy/workspace
	setenv LD_LIBRARY_PATH /scr0/mjuric/usr/lib
	setenv CONF_SDSS /scr0/mjuric/galaxy/workspace/$RUNSET/conf.sdss
	setenv BIN /scr0/mjuric/usr/bin
endif


set ddx = `echo "$DX0 * $NDX" | bc`
set ddx = `printf "%6.3f" $ddx`
setenv RI0 `printf "%.2f" $RI0`
setenv RI1 `printf "%.2f" $RI1`
set output = "cyl.$RI0-$RI1.txt"

echo Runset ID: $RUNSET
echo Photometric paralax: $PLX
echo "Creating cylindrical density map for bin ($RI0, $RI1), dx0=$DX0 ndx=$NDX dx=$ddx"
echo "Output file: $output"

cd $WORKSPACE/$RUNSET && \
time echo "new $output\n     paralax $PLX\n        cylindrical 15 21.5 $RI0 $RI1 $DX0 $NDX -180 $DX0 $NDX" | $BIN/selector.x \
  -s dmm/uniq_objects.dmm -o dmm/uniq_observations.dmm
